### ISSUE TITLE
Controller Category ID

### ISSUE THREAD

**Issue by reypryma** [arthara/SimplePOS-backend#10]

**Comment by AanMFA** [comment]
![image](https://user-images.githubusercontent.com/57135976/108089052-c282c280-70ab-11eb-9476-4564060e8883.png)
routenya belum bisa, soalnya nama kolomnya salah

**Comment by AanMFA** [comment]
![image](https://user-images.githubusercontent.com/57135976/108089345-12fa2000-70ac-11eb-9d34-d17feba18748.png)
harusnya user cumak bisa ngambil kategorinya sendiri per toko

**Comment by AanMFA** [comment]
![image](https://user-images.githubusercontent.com/57135976/108090161-e72b6a00-70ac-11eb-8dbd-2add637daa47.png)
sama kayak atas
